let frase1 = prompt("Por favor, introduzca una frase: ");
let frase2 = prompt("Y por último introduzca las dos otras frases: ");
document.write(`Longitud de frase1: \n${frase1.length}</br>`);
document.write(`Longitud de frase2: \n${frase2.length}</br>`);
document.write(`Subcadena [5:10] de frase1: \n${frase1.substring(5,10)}</br>`);
document.write(`Subcadena [5:10] de frase2: \n${frase2.substring(5,10)}</br>`);
document.write(`Subcadena con los 10 últimos caracteres de frase2:\n${frase2.slice(-10)}</br>`);
document.write(`Frase 1 pero sin el carácter à o á: \n${frase1.replace("á","a").replace("à","a")}</br>`);
document.write(`Frase2 en mayúsculas:\n${frase2.toUpperCase()}</br>`);
document.write(`Frase 1 sin espacios en los bordes: \n${frase1.trim()}</br>`);
document.write(`Primera letra e en frase 1: \nPosición nº${frase1.indexOf("e")}</br>`);
document.write(`Segunda letra e en la frase 1: \nPosición nº${frase1.indexOf("e",(frase1.indexOf("e")+1))}</br>`);
document.write(`Última letra e en frase 1: \nPosición nº${frase1.lastIndexOf("e")}</br>`);
document.write(`Frase 1 repetida 5 veces:\n${frase1.repeat(5)}</br>`);